//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Carousel = new HashSet<Carousel>();
            this.GoodsImg = new HashSet<GoodsImg>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.Order = new HashSet<Order>();
            this.AdminRecord = new HashSet<AdminRecord>();
        }
    
        public int GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string GoodsStyle { get; set; }
        public string GoodsIntro { get; set; }
        public int GoodsCount { get; set; }
        public int Price { get; set; }
        public int SalesCount { get; set; }
        public System.DateTime SaleTime { get; set; }
        public bool IfSale { get; set; }
        public int PurchasePrice { get; set; }
        public string Img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carousel> Carousel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsImg> GoodsImg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRecord> AdminRecord { get; set; }
    }
}
